#!/bin/bash
set -euo pipefail

declare DATA_DIR="./.data"
declare CONFIG_DIR="$DATA_DIR/config"
declare GRAYLOG_VERSION="2.1"

if [ ! -e "$CONFIG_DIR" ]; then
  echo "Getting default configuration"
  mkdir -p "$CONFIG_DIR"
  curl --silent -o "$CONFIG_DIR/graylog.conf" "https://raw.githubusercontent.com/Graylog2/graylog2-images/${GRAYLOG_VERSION}/docker/config/graylog.conf"
  curl --silent -o "$CONFIG_DIR/log4j2.xml" "https://github.com/Graylog2/graylog2-images/raw/${GRAYLOG_VERSION}/docker/config/log4j2.xml"

  echo "Generating node id"
  uuidgen > "$CONFIG_DIR/node-id"

  echo "Creating journal directory for graylog user"
  mkdir -p "$DATA_DIR/journal"
  sudo chown 1100 "$DATA_DIR/journal"

  echo "Setup done. Now edit the .* files."
  echo
  echo "Put the needed certificates into the .certs directory."
  echo "They will be available at /var/opt/graylog/data/certs from within the graylog container."
else
  echo "Config already exists. Aborting."
fi
